### ISSUE TITLE
能固定表头吗?

### ISSUE THREAD

**Issue by dengshenkk** [xiaoq1314/vue-table#2]
上下滚动时能固定表头吗?  左右滚动固定左侧

**Comment by xiaoq1314** [comment]
这个是单左右滚动的，单上下滚动也是一个原理，如果需要上下 左右 都能滚动的，可以留下你邮箱，我给你发一个demo

**Comment by dengshenkk** [comment]
建议完善这个项目吧 造福更多的人 @xiaoq1314

**Comment by Rain868** [comment]
同求demo  92381102@qq.com

**Comment by dengshenkk** [comment]
close

**Comment by xiaoq1314** [comment]
> 上下滚动时能固定表头吗? 左右滚动固定左侧

可以的，这个是个基础版的demo，只要你熟悉css，可以用样式去控制
